### ISSUE TITLE
Could you please provide a pre-trained model?

### ISSUE THREAD

**Issue by icbcbicc** [lzx1413/pytorch_face_landmark#1]
I'll appreciate if you could release a pre-trained model and relevant hyperparameters used for it.
Thanks a  lot!

**Comment by lzx1413** [comment]
I am sorry that I don't have a satisfying model yet. I just supplied a simple face landmark traing framework.

**Comment by icbcbicc** [comment]
Thanks. PyTorch based landmark detection implementations are really rare. You have done a nice job!
